services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-3000}
    restart: always
    container_name: cpen321_app
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "80:${PORT:-3000}"
    command: npm start
