services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-80}
    container_name: feastfriends
    restart: always
    environment:
    - PORT=${PROD_PORT}
    ports:
      - "${PORT}:${PORT}"
    command: npm start
