name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean remote backend folder
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            rm -rf /home/ubuntu/321-project/backend/*

      - name: Copy backend files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/*"
          target: "/home/ubuntu/321-project/backend"

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ubuntu/321-project/backend

            cat > .env << 'EOF'
            PORT=${{ secrets.PROD_PORT }}
            MONGODB_URI=${{ secrets.PROD_DB_URI }}
            JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.PROD_GOOGLE_CLIENT_ID }}
            GOOGLE_PLACES_API_KEY=${{ secrets.PROD_GOOGLE_PLACES_API_KEY }}
            EOF

            chmod 600 .env

            docker-compose --env-file .env down
            docker-compose --env-file .env build
            docker-compose --env-file .env up -d
